### ISSUE TITLE
Error when running amplian.py

### ISSUE THREAD

**Issue by nickjhathaway** [cbg-ethz/shorah#33]
Hi,
I'm trying to run amplian.py on some simulated data of mine for haplotypes but I have run into an error I don't know how to fix since I'm not sure what's causing it. 

I am running the latest version, downloaded from this link, https://github.com/cbg-ethz/shorah/releases/download/v1.1.0/shorah-1.1.0.tar.bz2 on Ubuntu 16.04 with python2 

The data I'm running with can be found here 

fastq: http://bib8.umassmed.edu/~hathawan/sim_7minor_1major_0/RSEQMID03.fastq
ref: http://bib8.umassmed.edu/~hathawan/sim_7minor_1major_0/major.fasta

This is simulated data so the reference is not a full genome.

I have tried creating a sorted bam file using bowtie2, bwa, and smalt and all three sorted bam files gave me the same error when I run the below command 

```bash
amplian.py -b RSEQMID03.sorted.bam -f major.fasta

```
And the error I get is copied below. 
```bash
Killed
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file amplian.py, line 63
Traceback (most recent call last):
  File "/usr/local/bin/amplian.py", line 429, in <module>
    args.s, args.region, args.diversity)
  File "/usr/local/bin/amplian.py", line 354, in main
    run_diagnostics(win_file, n_reads)
  File "/usr/local/bin/amplian.py", line 88, in run_diagnostics
    if new_clusters < q:
UnboundLocalError: local variable 'new_clusters' referenced before assignment
```

Any advice on what is happening? Sorry if it's something obvious on my end. 

Best,
Nick

**Comment by ozagordi** [comment]
Hi @nickjhathaway.
Thanks for testing shorah. Interestingly, I cannot reproduce your error. I aligned with 
`bwa mem major.fasta RSEQMID03.fastq > aln.sam` and then I did the usual conversion `samtools view -u aln.sam | samtools sort -T /tmp -@ 4 -o sorted.bam`. What I had after half an hour or so was
```
amplian.py -b sorted.bam -f major.fasta
/tmp/local/shorah/lib/python3.4/site-packages/shorah_snv.py:127: UserWarning: posterior = 1.059 > 1
  warnings.warn('posterior = %4.3f > 1' % post)
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
All reads in the same orientation?
```

Maybe I'm wrong, but I'm a bit puzzled by that `Killed` message on top of your error. Was it maybe killed accidentally, or by some other process?

**Comment by nickjhathaway** [comment]
Yes, sorry, stupid mistake on my part, the computer ran out of memory and it killed the job. I'll close.

Nick
