### ISSUE TITLE
ShoRAH.py error

### ISSUE THREAD

**Issue by woodford87** [cbg-ethz/shorah#43]
Hi, I've got the following error when running shorah.py against a 10KB genome with an illumina data set.

`Traceback (most recent call last):
  File "./shorah.py", line 139, in <module>
    alpha=args.a, keep_files=args.k, seed=args.S)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_dec.py", line 438, in main
    beg = int(parts[-2])
ValueError: invalid literal for int() with base 10: 'gb'`

The command line used to run this was:

`./shorah.py -b sorted.bam -f ref.fa`

Can anyone help with this error?

**Comment by woodford87** [comment]
I've managed to progress beyond this point by removing any '.' in my ref however, I am not getting the following error

`Traceback (most recent call last):
  File "./shorah.py", line 172, in <module>
    shorah_mm.main('%s_cor.rest' % in_stem, maxhaplo=2000)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 703, in main
    descList = findDescendants(graph)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 317, in findDescendants
    getDesc(i)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 311, in getDesc
    descList[node].update(getDesc(x))
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 311, in getDesc
    descList[node].update(getDesc(x))
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 311, in getDesc
    descList[node].update(getDesc(x))
  [Previous line repeated 992 more times]
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_mm.py", line 299, in getDesc
    if len(descList[node]) > 0:
RecursionError: maximum recursion depth exceeded in comparison`

Is anyone able to shed any light on this? I tried changing the max haplotypes in the shorah.py script (line 172) to 2000, instead of the default 200, but this hasn't helped.

**Comment by ozagordi** [comment]
Hi. Not sure how to help here. I must say that we don't really support/promote global reconstruction with shorah anymore, see also _A word of caution_ [here](http://cbg-ethz.github.io/shorah/global.html). You might be luckier with other tools, but always keeping in mind the intrinsic limitations of the approach. I'm closing this now because we plan to remove global reconstruction from shorah anyway.

Thanks for understanding.
