### ISSUE TITLE
dec.py error "line 582, in main     (kp, proposed[kp][0] / proposed[kp][1]))"

### ISSUE THREAD

**Issue by KabitaBaral1** [cbg-ethz/shorah#64]
Hi,
I am running your program to detect haplotype frequency across 20 samples with a malaria gene. In every case, my amplicon can vary from 120 bp to 1100 bp (it is length polymorphic), and I performed a sequencing process with Illumina MiSeq in pair-end mode using 2x250, so as you can see I have shorter reads than my amplicon. First I did mapping to my reference, then sorted every sam file, and tried running the local analysis using `dec.py`. However, after I run it using  `dec.py -b s11msp1.mapped.bam.sam.bam -f pf_msp1.fasta -w 300 -k`, the output I get is:

```
/gpfs/home/kbaral/anaconda3/envs/shorah/bin/diri_sampler/gpfs/home/kbaral/anaconda3/envs/shorah/bin/diri_sampler: error while loading shared libraries: libopenblas.so.0: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
/gpfs/home/kbaral/anaconda3/envs/shorah/bin/diri_sampler: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
: cannot open shared object file: No such file or directory
{0: 1756}
Traceback (most recent call last):
  File "/home/kbaral/anaconda3/envs/shorah/bin/dec.py", line 78, in <module>
    args.region, args.max_coverage, args.alpha, args.keep_files, args.seed)
  File "/home/kbaral/anaconda3/envs/shorah/lib/python3.5/site-packages/shorah_dec.py", line 582, in main
    (kp, proposed[kp][0] / proposed[kp][1]))
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

Do you know what could be happening here?

Thanks in advance,

Kabita

**Comment by KabitaBaral1** [comment]
I figured out my problem was with my sam alignment. The code has run just fine with the latest version as well.
