### ISSUE TITLE
Conda package: no version file

### ISSUE THREAD

**Issue by stefanches7** [cbg-ethz/shorah#76]
See error report below:
```
(shorah) [dvoretsk@ouga03 REGION_1]$ shorah
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/shorah/cli.py", line 50, in <module>
    __version__ = get_distribution('shorah').version
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'shorah' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/shorah/bin/shorah", line 11, in <module>
    from shorah.cli import main
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/shorah/cli.py", line 53, in <module>
    with open(os.path.join(base_dir, '.version'), 'r') as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/modules/i12g/anaconda/envs/shorah/.version'
(shorah) [dvoretsk@ouga03 REGION_1]$ shorah
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/shorah/cli.py", line 50, in <module>
    __version__ = get_distribution('shorah').version
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'shorah' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/shorah/bin/shorah", line 11, in <module>
    from shorah.cli import main
  File "/opt/modules/i12g/anaconda/envs/shorah/lib/python3.6/site-packages/shorah/cli.py", line 53, in <module>
    with open(os.path.join(base_dir, '.version'), 'r') as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/modules/i12g/anaconda/envs/shorah/.version'
(shorah) [dvoretsk@ouga03 REGION_1]$ conda install shorah
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

**Comment by DrYak** [comment]
Hello, this is a duplicate of issue #72 
It seem to have been fixed in PR #71 
I am waiting for my colleagues' code review and we'll release version 1.99.1 on Bioconda.

(I am currently testing the 1.99.1 bioconda package with [the recipe in this branch](https://github.com/DrYak/bioconda-recipes/tree/update_shorah) )

**Comment by DrYak** [comment]
BTW: until the package is ready, the work-around is: _do not call your environment 'shorah'_

**Comment by DrYak** [comment]
The new 1.99.1 package has been merged into bioconda.
It should be appearing on bioconda soon.

Could you give it a try in the coming days ?

**Comment by DrYak** [comment]
We have updated 1.99.1 to 1.99.2 (change of API usage into HTSlib  to fix a crash introduced by version 1.10.2, see #77).

Did you get to test the newer version? Did it fix your problems?
