### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by woodford87** [cbg-ethz/shorah#79]

**Comment by woodford87** [comment]
ok, a bit more info. I reduced the window size even further, to 100bp, assuming that this error is because the window is larger than the read sizes. This wasn't an issue with previous runs I have done using Shorah.

It now produces the following error:

`shorah amplicon -b /Users/lw86/shorah-1.1.3/bin/P290A-74-S74.sorted.bam  -f /Users/lw86/shorah-1.1.3/bin/DWV_VVD9_ref_trim.fa -r DWV_VVD9:2000-2100 
Traceback (most recent call last):
  File "/Users/lw86/anaconda3/bin/shorah", line 14, in <module>
    main()
  File "/Users/lw86/anaconda3/lib/python3.7/site-packages/shorah/cli.py", line 210, in main
    args.func(args)
  File "/Users/lw86/anaconda3/lib/python3.7/site-packages/shorah/cli.py", line 89, in amplicon_run
    amplicon.main(args)
  File "/Users/lw86/anaconda3/lib/python3.7/site-packages/shorah/amplicon.py", line 397, in main
    run_diagnostics(win_file, n_reads)
  File "/Users/lw86/anaconda3/lib/python3.7/site-packages/shorah/amplicon.py", line 118, in run_diagnostics
    lines = l.readlines()
  File "/Users/lw86/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 258: invalid continuation byte
`
Does anyone know what is causing this? 
Thanks, Luke

**Comment by woodford87** [comment]
I have resolved this issue. Thanks.

**Comment by DrYak** [comment]
You were faster than me!

(In general, unless you rely on a feature which is not available in ShoRAH2, such as global haplotype, I would strongly encourage users to switch to the latest ShoRAH2 package, currently 1.99.2. See the [shorah releases](https://github.com/cbg-ethz/shorah/releases/) or the [corresponding bioconda packages](https://bioconda.github.io/recipes/shorah/README.html) )

**Comment by woodford87** [comment]
Thanks for replying anyway!

I have switched to shorah2, as you suggested. I actually did rely on the global haplotype feature previously, but I can get by with local haplotype in Shorah2.

Thanks again
